INSERT INTO transport_models (model, type_brand_id)
VALUES ('Corolla', 1),
       ('Camry', 1),
       ('Avalon', 1),
       ('Mirai', 1),
       ('Crown', 1),
       ('RAV4', 1),
       ('Highlander', 1),
       ('Venza', 1),
       ('bZ4X', 1),
       ('C-HR', 1),
       ('Corolla Cross', 1),
       ('Yaris Cross', 1),
       ('Land Cruiser Prado', 1),
       ('Land Cruiser', 1),
       ('FJ Cruiser', 1),
       ('Hilux', 1),
       ('Tacoma', 1),
       ('GR86', 1),
       ('Yaris', 1),
       ('Corolla Hatchback', 1),
       ('GR Yaris', 1),
       ('Supra', 1),
       ('GR Supra', 1),
       ('Sienna', 1),
       ('Alphard', 1),
       ('Vellfire', 1);

INSERT INTO transport_models (model, type_brand_id)
VALUES ('Focus', 2),
       ('Fusion', 2),
       ('Mondeo', 2),
       ('Taurus', 2),
       ('EcoSport', 2),
       ('Escape', 2),
       ('Edge', 2),
       ('Explorer', 2),
       ('F-150', 2),
       ('Maverick', 2),
       ('Bronco', 2),
       ('Bronco Sport', 2),
       ('Expedition', 2),
       ('Expedition Max', 2),
       ('Mustang', 2),
       ('Fiesta', 2),
       ('Mustang Mach-E', 2);

INSERT INTO transport_models (model, type_brand_id)
VALUES ('Malibu', 3),
       ('Impala', 3),
       ('Trax', 3),
       ('Trailblazer', 3),
       ('Equinox', 3),
       ('Blazer', 3),
       ('Bolt EV', 3),
       ('Bolt EUV', 3),
       ('Tahoe', 3),
       ('Suburban', 3),
       ('Camaro', 3),
       ('Corvette', 3),
       ('Silverado', 3),
       ('Avalanche', 3),
       ('Camaro', 3),
       ('Spark', 3);

INSERT INTO transport_models (model, type_brand_id)
VALUES ('Accord', 4),
       ('Civic', 4),
       ('Insight', 4),
       ('Odyssey', 4),
       ('Pilot', 4),
       ('HR-V', 4),
       ('CR-V', 4),
       ('ZR-V', 4),
       ('Passport', 4),
       ('Ridgeline', 4),
       ('Civic Type R', 4),
       ('Civic Hatchback', 4),
       ('Jazz', 4),
       ('NSX', 4);

INSERT INTO transport_models (model, type_brand_id)
VALUES ('Phaeton', 5),
       ('Passat', 5),
       ('Arteon', 5),
       ('Touareg', 5),
       ('ID.4', 5),
       ('ID.6', 5),
       ('Scirocco', 5),
       ('Golf', 5),
       ('Golf GTI', 5),
       ('Golf R', 5),
       ('Golf Cabriolet', 5),
       ('Golf R32', 5),
       ('Golf R Variant', 5),
       ('Scirocco R', 5),
       ('ID.3', 5),
       ('ID.5', 5),
       ('XL1', 5);

INSERT INTO transport_models (model, type_brand_id)
VALUES ('Altima', 6),
       ('Maxima', 6),
       ('Cedric', 6),
       ('Gloria', 6),
       ('Laurel', 6),
       ('Skyline', 6),
       ('Sylphy', 6),
       ('Teana', 6),
       ('Kicks', 6),
       ('Murano', 6),
       ('Pathfinder', 6),
       ('Qashqai', 6),
       ('Rogue', 6),
       ('X-Trail', 6),
       ('370Z', 6),
       ('Fairlady Z', 6),
       ('GT-R', 6),
       ('Silvia', 6),
       ('Almera', 6),
       ('Leaf', 6),
       ('Micra', 6),
       ('Note', 6),
       ('Pulsar', 6),
       ('Sentra', 6),
       ('Sunny', 6),
       ('370Z', 6),
       ('Fairlady Z', 6),
       ('GT-R', 6),
       ('Silvia', 6),
       ('Caravan', 6),
       ('Elgrand', 6),
       ('NV350', 6),
       ('Serena', 6),
       ('Frontier', 6),
       ('Navara', 6);

INSERT INTO transport_models (model, type_brand_id)
VALUES ('1 Series', 7),
       ('2 Series', 7),
       ('3 Series', 7),
       ('4 Series', 7),
       ('5 Series', 7),
       ('6 Series', 7),
       ('7 Series', 7),
       ('8 Series', 7),
       ('M2', 7),
       ('M3', 7),
       ('M4', 7),
       ('M5', 7),
       ('M6', 7),
       ('M8', 7),
       ('Gran Turismo', 7),
       ('X1', 7),
       ('X2', 7),
       ('X3', 7),
       ('X4', 7),
       ('X5', 7),
       ('X6', 7),
       ('X7', 7),
       ('2 Series Gran Coupe', 7),
       ('4 Series Gran Coupe', 7),
       ('8 Series Gran Coupe', 7),
       ('1 Series', 7),
       ('2 Series Active Tourer', 7),
       ('2 Series Gran Tourer', 7),
       ('Z4', 7),
       ('i8', 7);
INSERT INTO transport_models (model, type_brand_id)
VALUES ('A-Class', 8),
       ('B-Class', 8),
       ('C-Class', 8),
       ('CLS-Class', 8),
       ('CLA-Class', 8),
       ('E-Class', 8),
       ('GLA-Class', 8),
       ('GLC-Class', 8),
       ('GLE-Class', 8),
       ('GLS-Class', 8),
       ('S-Class', 8),
       ('SL-Class', 8),
       ('SLS AMG', 8),
       ('Maybach', 8),
       ('AMG GT', 8);

INSERT INTO transport_models (model, type_brand_id)
VALUES ('A1', 9),
       ('A3', 9),
       ('A4', 9),
       ('A5', 9),
       ('A6', 9),
       ('A7', 9),
       ('A8', 9),
       ('S1', 9),
       ('S3', 9),
       ('S4', 9),
       ('S5', 9),
       ('S6', 9),
       ('S7', 9),
       ('S8', 9),
       ('RS 1', 9),
       ('RS 3', 9),
       ('RS 4', 9),
       ('RS 5', 9),
       ('RS 6', 9),
       ('RS 7', 9),
       ('RS 8', 9),
       ('Q2', 9),
       ('Q3', 9),
       ('Q3 Sportback', 9),
       ('Q5', 9),
       ('Q5 Sportback', 9),
       ('Q7', 9),
       ('Q8', 9),
       ('SQ2', 9),
       ('SQ5', 9),
       ('SQ7', 9),
       ('SQ8', 9),
       ('RSQ3', 9),
       ('RS Q3', 9),
       ('RS Q5', 9),
       ('RS Q7', 9),
       ('RS Q8', 9),
       ('TT', 9),
       ('TT RS', 9);

INSERT INTO transport_models (model, type_brand_id)
VALUES ('Accent', 10),
       ('Elantra', 10),
       ('Sonata', 10),
       ('Grandeur', 10),
       ('Equus', 10),
       ('Genesis', 10),
       ('Azera', 10),
       ('Creta', 10),
       ('Tucson', 10),
       ('Santa Fe', 10),
       ('Palisade', 10),
       ('Kona', 10),
       ('Nexo', 10),
       ('Ioniq 5', 10),
       ('Ioniq 7', 10),
       ('Veloster', 10),
       ('Genesis Coupe', 10),
       ('i10', 10),
       ('i20', 10),
       ('i30', 10),
       ('i40', 10),
       ('Veloster N', 10),
       ('Genesis Coupe N', 10),
       ('H-1', 10);

INSERT INTO transport_models (model, type_brand_id)
VALUES ('Pride', 11),
       ('Cerato', 11),
       ('Optima', 11),
       ('K5', 11),
       ('Stinger', 11),
       ('K9', 11),
       ('Cadenza', 11),
       ('Sportage', 11),
       ('Sorento', 11),
       ('Telluride', 11),
       ('Soul', 11),
       ('Niro', 11),
       ('EV6', 11),
       ('XCeed', 11),
       ('Forte Koup', 11),
       ('Stinger', 11),
       ('Rio', 11),
       ('Picanto', 11),
       ('Cerato Koup', 11),
       ('Forte Koup', 11),
       ('Forte', 11),
       ('Cee''d', 11),
       ('Soul', 11),
       ('Niro', 11),
       ('XCeed', 11),
       ('ProCeed', 11),
       ('Stinger', 11),
       ('Carnival', 11);

INSERT INTO transport_models (model, type_brand_id)
VALUES ('Legacy', 12),
       ('Impreza', 12),
       ('WRX', 12),
       ('WRX STI', 12),
       ('Levorg', 12),
       ('Forester', 12),
       ('Outback', 12),
       ('XV Crosstrek', 12),
       ('Solterra', 12),
       ('BRZ', 12);

INSERT INTO transport_models (model, type_brand_id)
VALUES ('Renegade', 13),
       ('Compass', 13),
       ('Cherokee', 13),
       ('Grand Cherokee', 13),
       ('Wagoneer', 13),
       ('Grand Wagoneer', 13),
       ('Gladiator', 13),
       ('Wrangler', 13),
       ('Wrangler Unlimited', 13);

INSERT INTO transport_models (model, type_brand_id)
VALUES ('Ram 1500', 14),
       ('Ram 2500', 14),
       ('Ram 3500', 14),
       ('Ram 4500', 14),
       ('Ram 5500', 14),
       ('Ram Power Wagon', 14),
       ('Ram Rebel', 14),
       ('Ram Warlock', 14),
       ('Ram SRT-10', 14),
       ('Ram Dakota', 14),
       ('Ram Van', 14),
       ('Ram Cargo Van', 14),
       ('Ram ProMaster', 14),
       ('Ram ProMaster City', 14);

INSERT INTO transport_models (model, type_brand_id)
VALUES ('Dart', 15),
       ('Avenger', 15),
       ('Charger', 15),
       ('Challenger', 15),
       ('Monaco', 15),
       ('Coronet', 15),
       ('Dart Swinger', 15),
       ('Dart GT', 15),
       ('Charger Daytona', 15),
       ('Challenger R/T', 15),
       ('Charger Hellcat', 15),
       ('Challenger Hellcat Redeye', 15),
       ('Journey', 15),
       ('Dakota', 15),
       ('Ram 1500', 15),
       ('Ram 2500', 15),
       ('Ram 3500', 15);

INSERT INTO transport_models (model, type_brand_id)
VALUES ('Canyon', 16),
       ('Sierra', 16),
       ('Sierra Denali', 16),
       ('Sierra HD', 16),
       ('Sierra 1500', 16),
       ('Sierra 2500', 16),
       ('Sierra 3500', 16),
       ('Hummer EV', 16),
       ('Hummer EV SUV', 16),
       ('Acadia', 16),
       ('Terrain', 16),
       ('Terrain Denali', 16),
       ('Savana', 16),
       ('Yukon', 16),
       ('Yukon Denali', 16),
       ('Yukon XL', 16),
       ('Yukon XL Denali', 16);

INSERT INTO transport_models (model, type_brand_id)
VALUES ('Familia', 17),
       ('Capella', 17),
       ('Cosmo', 17),
       ('RX-7', 17),
       ('RX-8', 17),
       ('929', 17),
       ('626', 17),
       ('323', 17),
       ('3', 17),
       ('6', 17),
       ('Mazda6', 17),
       ('Mazda3', 17),
       ('Mazda2', 17),
       ('CX-3', 17),
       ('CX-30', 17),
       ('CX-5', 17),
       ('CX-7', 17),
       ('CX-9', 17),
       ('Mazda5', 17),
       ('BT-50', 17),
       ('MX-5', 17);

INSERT INTO transport_models (model, type_brand_id)
VALUES ('CT', 18),
       ('ES', 18),
       ('GS', 18),
       ('GX', 18),
       ('IS', 18),
       ('LC', 18),
       ('LS', 18),
       ('LX', 18),
       ('NX', 18),
       ('RC', 18),
       ('RX', 18),
       ('UX', 18);

INSERT INTO transport_models (model, type_brand_id)
VALUES ('CT4', 19),
       ('CT5', 19),
       ('CT6', 19),
       ('Escalade', 19),
       ('Escalade ESV', 19),
       ('Escalade EXT', 19),
       ('CTS', 19),
       ('CTS-V', 19),
       ('DeVille', 19),
       ('Eldorado', 19),
       ('Fleetwood', 19),
       ('Seville', 19),
       ('STS', 19),
       ('STS-V', 19),
       ('XLR', 19),
       ('XTS', 19);

INSERT INTO transport_models (model, type_brand_id)
VALUES ('300', 20),
       ('Aspen', 20),
       ('Cirrus', 20),
       ('Concorde', 20),
       ('Cordoba', 20),
       ('Crossfire', 20),
       ('Dart', 20),
       ('Daytona', 20),
       ('Imperial', 20),
       ('LHS', 20),
       ('New Yorker', 20),
       ('Pacifica', 20),
       ('PT Cruiser', 20),
       ('Sebring', 20),
       ('Town & Country', 20),
       ('Voyager', 20);

INSERT INTO transport_models (model, type_brand_id)
VALUES ('ILX', 21),
       ('TLX', 21),
       ('RLX', 21),
       ('Legend', 21),
       ('NSX', 21),
       ('Integra', 21),
       ('MDX', 21),
       ('MDX PMC Edition', 21);

INSERT INTO transport_models (model, type_brand_id)
VALUES ('Q30', 22),
       ('Q50', 22),
       ('Q60', 22),
       ('Q70', 22),
       ('QX30', 22),
       ('QX50', 22),
       ('QX60', 22),
       ('QX70', 22),
       ('QX80', 22);

INSERT INTO transport_models (model, type_brand_id)
VALUES ('S40', 23),
       ('V40', 23),
       ('S60', 23),
       ('V60', 23),
       ('C70', 23),
       ('S70', 23),
       ('V70', 23),
       ('S80', 23),
       ('V80', 23),
       ('XC70', 23),
       ('XC90', 23),
       ('C30', 23),
       ('S60 Cross Country', 23),
       ('V60 Cross Country', 23),
       ('XC60', 23),
       ('S90', 23),
       ('V90', 23),
       ('XC40', 23),
       ('C40 Recharge', 23),
       ('EX30', 23),
       ('EX30 Cross Country', 23),
       ('EX90', 23);
