INSERT INTO transport_views (user_id, transport_id, created, last_update)
VALUES
    (1, 1, now(), now()),
    (1, 2, now(), now()),
    (1, 3, now(), now()),
    (1, 4, now(), now()),
    (1, 5, now(), now()),
    (1, 6, now(), now()),
    (1, 7, now(), now()),
    (1, 8, now(), now()),
    (1, 9, now(), now()),
    (1, 10, now(), now()),
    (1, 11, now(), now()),
    (1, 12, now(), now()),
    (1, 13, now(), now()),
    (1, 14, now(), now()),
    (1, 15, now(), now()),
    (1, 16, now(), now()),
    (1, 17, now(), now()),
    (1, 18, now(), now()),
    (1, 19, now(), now()),


    (2, 6, now(), now()),
    (2, 7, now(), now()),
    (2, 8, now(), now()),
    (2, 9, now(), now()),
    (2, 10, now(), now()),
    (2, 15, now(), now()),
    (2, 16, now(), now()),
    (2, 17, now(), now()),
    (2, 18, now(), now()),
    (2, 19, now(), now()),
    (2, 11, now(), now());
